/- Generated by Juniper's finite ground model.
   Generic implication proofs, NOT a mathematical source reifier.
   This file has not been compiled in the supplied environment. -/
set_option autoImplicit false
namespace JuniperGenerated

-- Need QuotientReady; additional premises: DirectGerm, Positive
theorem need_0_route_0
    (A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 : Prop)
    (r0 : A0 -> A1 -> A2 -> A3)
    (r1 : A8 -> A3)
    (r2 : A3 -> A4)
    (r3 : A5 -> A6)
    (r4 : A4 -> A6 -> A7)
    (r5 : A9 -> A9)
    (k0 : A0)
    (k1 : A2)
    (h0 : A8)
    (h1 : A5)
    : A7 := by
  have n3 : A8 := h0
  have n4 : A5 := h1
  have n6 : A3 := r1 n3
  have n8 : A4 := r2 n6
  have n9 : A6 := r3 n4
  have n11 : A7 := r4 n8 n9
  exact n11

-- Need QuotientReady; additional premises: Open, Positive
theorem need_0_route_1
    (A0 A1 A2 A3 A4 A5 A6 A7 A8 A9 : Prop)
    (r0 : A0 -> A1 -> A2 -> A3)
    (r1 : A8 -> A3)
    (r2 : A3 -> A4)
    (r3 : A5 -> A6)
    (r4 : A4 -> A6 -> A7)
    (r5 : A9 -> A9)
    (k0 : A0)
    (k1 : A2)
    (h0 : A1)
    (h1 : A5)
    : A7 := by
  have n0 : A0 := k0
  have n1 : A2 := k1
  have n2 : A1 := h0
  have n4 : A5 := h1
  have n5 : A3 := r0 n0 n2 n1
  have n7 : A4 := r2 n5
  have n9 : A6 := r3 n4
  have n10 : A7 := r4 n7 n9
  exact n10

end JuniperGenerated
