-- Generated by the restricted Python model; NOT compiled in this run.
import CloverCore
set_option autoImplicit false
universe u
namespace CloverGenerated
open CloverCore

theorem composite (A : Type u)
    (f_1 g_2 r_3 k_4 : A -> A)
    (retraction_5 : LeftInverse r_3 f_1)
    (outer_6 : Injective g_2)
    : Injective (compose g_2 f_1) := by
  have clover_step_1 : Injective f_1 := inj_from_left_inverse f_1 r_3 retraction_5
  have clover_step_3 : Injective (compose g_2 f_1) := inj_comp f_1 g_2 clover_step_1 outer_6
  exact clover_step_3

theorem transported (A : Type u)
    (f_1 g_2 r_3 k_4 : A -> A)
    (retraction_5 : LeftInverse r_3 f_1)
    (outer_6 : Injective g_2)
    (renamed_7 : Same g_2 k_4)
    : Injective (compose k_4 f_1) := by
  have clover_step_1 : Injective f_1 := inj_from_left_inverse f_1 r_3 retraction_5
  have clover_step_4 : Injective k_4 := inj_transport g_2 k_4 renamed_7 outer_6
  have clover_step_5 : Injective (compose k_4 f_1) := inj_comp f_1 k_4 clover_step_1 clover_step_4
  exact clover_step_5

theorem local_composite (A : Type u)
    (f_1 g_2 r_3 k_4 j_8 : A -> A)
    (retraction_5 : LeftInverse r_3 f_1)
    (outer_6 : Injective g_2)
    (renamed_7 : Same g_2 k_4)
    (local_9 : Involutive j_8)
    : Injective (compose j_8 f_1) := by
  have clover_step_1 : Injective f_1 := inj_from_left_inverse f_1 r_3 retraction_5
  have clover_step_3 : LeftInverse j_8 j_8 := inv_from_involution j_8 local_9
  have clover_step_4 : Injective j_8 := inj_from_left_inverse j_8 j_8 clover_step_3
  have clover_step_5 : Injective (compose j_8 f_1) := inj_comp f_1 j_8 clover_step_1 clover_step_4
  exact clover_step_5

-- unsupported_strengthening: unresolved; no theorem exported.

end CloverGenerated
